CREATE DATABASE djuncao;
USE djuncao;

CREATE TABLE CARGO (
    CodCargo CHAR(2) PRIMARY KEY,
    NomeCargo VARCHAR(50) NULL,
    ValorCargo FLOAT NULL
);

CREATE TABLE FUNCIONARIO (
    Matricula INT PRIMARY KEY,
    NomeFuncionario VARCHAR(50) NOT NULL,
    CodCargo CHAR(2) NULL,
    FOREIGN KEY (CodCargo) REFERENCES CARGO(CodCargo)
);

INSERT INTO CARGO (CodCargo, NomeCargo, ValorCargo) VALUES 
('C1', 'CAIXA', 800.00),
('C2', 'VENDEDOR', 1200.00),
('C3', 'GERENTE', 2400.00);

INSERT INTO FUNCIONARIO (Matricula, NomeFuncionario, CodCargo) VALUES 
(100, 'JOÃO', 'C1'),
(110, 'MARIA', 'C2'),
(120, 'CARLOS', 'C1'),
(130, 'TADEU', NULL);

-- Questão 5
SELECT FUNCIONARIO.NomeFuncionario, CARGO.NomeCargo
FROM FUNCIONARIO
INNER JOIN CARGO ON FUNCIONARIO.CodCargo = CARGO.CodCargo;

-- Questão 6
SELECT FUNCIONARIO.NomeFuncionario, CARGO.NomeCargo
FROM FUNCIONARIO
RIGHT JOIN CARGO ON FUNCIONARIO.CodCargo = CARGO.CodCargo;

-- Questão 7
SELECT FUNCIONARIO.NomeFuncionario, CARGO.NomeCargo
FROM FUNCIONARIO
LEFT JOIN CARGO ON FUNCIONARIO.CodCargo = CARGO.CodCargo;

-- Questão 8
SELECT FUNCIONARIO.NomeFuncionario
FROM FUNCIONARIO
INNER JOIN CARGO ON FUNCIONARIO.CodCargo = CARGO.CodCargo
WHERE CARGO.NomeCargo = 'CAIXA';

-- Questão 9
SELECT FUNCIONARIO.NomeFuncionario, CARGO.NomeCargo
FROM FUNCIONARIO
INNER JOIN CARGO ON FUNCIONARIO.CodCargo = CARGO.CodCargo
WHERE CARGO.ValorCargo > 1000.00;